Add SourceKit Validation smoke test

diff --git a/.github/workflows/swift-toolchain.yml b/.github/workflows/swift-toolchain.yml
--- a/.github/workflows/swift-toolchain.yml
+++ b/.github/workflows/swift-toolchain.yml
@@ -2431,6 +2431,10 @@ jobs:
     runs-on: ${{ needs.context.outputs.windows_build_runner }}
 
     steps:
+      - uses: actions/checkout@v4
+        with:
+          sparse-checkout: tests
+
       - uses: actions/download-artifact@v4
         with:
           name: installer-amd64
@@ -2482,6 +2486,27 @@ jobs:
 
       - run: swift test -Xswiftc -DENABLE_TESTING
         working-directory: ${{ github.workspace }}/SourceCache/swift-win32
+
+      - name: SourceKit Validation
+        id: sourcekit-validation
+        working-directory: ${{ github.workspace }}/SourceCache/swift-win32
+        continue-on-error: true
+        run: |
+          $diagnosticOutput = $( $output = & Get-Content ${{ github.workspace }}/tests/sourcekit-lsp-initialization-message | sourcekit-lsp.exe ) 2>&1
+          if (-not ($diagnosticOutput -Match "Succeeded") -or -not ($diagnosticOutput -Match "InitializeResult")) {
+            Write-Host "sourcekit-lsp failed to initialize"
+            Write-Host $diagnosticOutput
+            echo "failed=true" >> $GITHUB_OUTPUT
+          } else {
+            echo "failed=false" >> $GITHUB_OUTPUT
+          }
+      
+      - name: SourceKit Validation Check
+        run: |
+          if (${{ steps.sourcekit-validation.outputs.failed == 'true' }}) {
+            Write-Host "sourcekit-lsp failed to initialize"
+            exit 1
+          }
 
   snapshot:
     runs-on: ubuntu-latest
