Move robocopy to after all artifacts were downloaded

diff --git a/.github/workflows/swift-toolchain.yml b/.github/workflows/swift-toolchain.yml
--- a/.github/workflows/swift-toolchain.yml
+++ b/.github/workflows/swift-toolchain.yml
@@ -4631,35 +4631,6 @@ jobs:
         with:
           name: Windows-${{ matrix.arch }}-NoAsserts-compilers
           path: ${{ github.workspace }}/BuildRoot/Library
-
-      - name: Complete NoAsserts layout
-        run: |
-          $AssertToolchainRoot = "${{ github.workspace }}\BuildRoot\Library\Developer\Toolchains\${{ inputs.swift_version }}+Asserts"
-          $NoAssertToolchainRoot = "${{ github.workspace }}\BuildRoot\Library\Developer\Toolchains\${{ inputs.swift_version }}+NoAsserts"
-          $LogFile = "${{ github.workspace }}\robocopy-${{ matrix.arch }}.log"
-          # Only compilers have NoAsserts enabled. Copy the rest of the Toolcahin binaries from the Asserts output
-          # Use robocopy for efficient copying
-          #   /E : Copies subdirectories, including empty ones.
-          #   /XC: Excludes existing files with the same timestamp but different file sizes.
-          #   /XN: Excludes existing files that are newer than the copy in the source directory.
-          #   /XO: Excludes existing files that are older than the copy in the source directory.
-          #   /NFL: Do not list coppied files in output
-          #   /NDL: Do not list directories in output
-          #   /NJH: Do not write a job header
-          #   /NC: Do not write file classes
-          #   /NS: Do not write file sizes
-          #   /NP: Do not show progress indicator
-          #   /R:3                - Retry 3 times on failed copies
-          #   /W:5                - Wait 5 seconds between retries
-          #   /LOG:"D:\robocopy.log" - Write output to a log file
-          &robocopy $AssertToolchainRoot $NoAssertToolchainRoot /E /XC /XN /XO /NS /NC /NFL /NDL /NJH /R:3 /W:5 /LOG:"$LogFile"
-    
-      - name: Uploas robocopy log
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: robocopy-${{ matrix.arch }}.log
-          path: ${{ github.workspace }}\robocopy-${{ matrix.arch }}.log
       
       - name: Download Developer Tools
         uses: actions/download-artifact@v4
@@ -4742,6 +4713,36 @@ jobs:
             Install-Package -Name WixToolset.Sdk -RequiredVersion 4.0.1 -Force
           }
 
+      - name: Complete NoAsserts layout
+        run: |
+          $AssertToolchainRoot = "${{ github.workspace }}\BuildRoot\Library\Developer\Toolchains\${{ inputs.swift_version }}+Asserts"
+          $NoAssertToolchainRoot = "${{ github.workspace }}\BuildRoot\Library\Developer\Toolchains\${{ inputs.swift_version }}+NoAsserts"
+          $LogFile = "${{ github.workspace }}\robocopy-${{ matrix.arch }}.log"
+          # Only compilers have NoAsserts enabled. Copy the rest of the Toolcahin binaries from the Asserts output
+          # Use robocopy for efficient copying
+          #   /E : Copies subdirectories, including empty ones.
+          #   /XC: Excludes existing files with the same timestamp but different file sizes.
+          #   /XN: Excludes existing files that are newer than the copy in the source directory.
+          #   /XO: Excludes existing files that are older than the copy in the source directory.
+          #   /NFL: Do not list coppied files in output
+          #   /NDL: Do not list directories in output
+          #   /NJH: Do not write a job header
+          #   /NC: Do not write file classes
+          #   /NS: Do not write file sizes
+          #   /NP: Do not show progress indicator
+          # $exitCode = &robocopy $HostPlatform.ToolchainInstallRoot $HostPlatform.NoAssertsToolchainInstallRoot /E /XC /XN /XO /NS /NC /NFL /NDL /NJH
+          $exitCode = &robocopy $AssertToolchainRoot $NoAssertToolchainRoot /E /XC /XN /XO /R:3 /W:5 /LOG:"$LogFile"
+          if ($LASTEXITCODE -gt 8) {
+              Write-Error "robocopy failed with exit code $LASTEXITCODE"
+              exit $LASTEXITCODE
+          }
+      - name: Uploas robocopy log
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: robocopy-${{ matrix.arch }}.log
+          path: ${{ github.workspace }}\robocopy-${{ matrix.arch }}.log
+
       - uses: actions/checkout@v4.2.2
         with:
           repository: microsoft/mimalloc
@@ -4803,7 +4804,7 @@ jobs:
 
       - name: Package Build Tools (NoAsserts)
         run: |
-          # When cross-compiling, bundle the second mimalloc redirect dll as a workaround for
+         # When cross-compiling, bundle the second mimalloc redirect dll as a workaround for
           msbuild -nologo -restore -maxCpuCount `
               -p:BaseOutputPath=${{ github.workspace }}\BinaryCache\installer\ `
               -p:Configuration=Release `
